### ISSUE TITLE
sync bug

### ISSUE THREAD

**Issue by c3cilia** [tunapanda/wp-remote-sync#20]
For some reason one particular post "design-3" seems to be created different in the local wordpress when doing a pull.

********************************************************************************************************************

Pull: post
**** Tried to save, but that changed the revision, slug=design-3
**** Remote:
{
    "post_name": "design-3",
    "post_title": "2D Graphics and Animations",
    "post_type": "page",
    "post_content": "[course-listing]",
    "post_excerpt": "This track covers 2-dimensional graphics and animation tutorials: raster, vector and free hand-drawn objects.",
    "post_status": "publish",
    "post_parent": "design",
    "menu_order": 0,
    "meta": []
}
**** Local:
{
    "post_name": "design-3",
    "post_title": "2D Graphics and Animations",
    "post_type": "page",
    "post_content": "[course-listing]",
    "post_excerpt": "This track covers 2-dimensional graphics and animation tutorials: raster, vector and free hand-drawn objects.",
    "post_status": "publish",
    "post_parent": "",
    "menu_order": 0,
    "meta": []
}
** Error **
design-3: Local revision differ from remote after create.
#0 /home/cess/Documents/tizi/my-wp-theme/wp-content/plugins/wp-remote-sync/src/controller/RemoteSyncOperations.php(161): SyncResource->createLocalResource()
#1 [internal function]: RemoteSyncOperations->pull()
#2 /home/cess/Documents/tizi/my-wp-theme/wp-content/plugins/wp-remote-sync/src/controller/RemoteSyncOperations.php(42): call_user_func(Array)
#3 /home/cess/Documents/tizi/my-wp-theme/wp-content/plugins/wp-remote-sync/op.php(16): RemoteSyncOperations->handleOperation('Pull')
#4 {main}

**Comment by c3c1l1a** [comment]
![image](https://cloud.githubusercontent.com/assets/8858461/18624767/c4ec74c6-7e52-11e6-8f92-f7436a3f1dfa.png)

Another similar bug.

**Comment by limikael** [comment]
Both of these should be fixed on this branch:

https://github.com/tunapanda/wp-remote-sync/tree/sync_h5p_by_package

However... I will wait a bit to merge it in, since the protocol has changed a bit, I.e. both the local and the remote needs the new version of the plugin.

**Comment by limikael** [comment]
So should be fixed! Please verify @c3c1l1a
