### ISSUE TITLE
Error when activating plugin

### ISSUE THREAD

**Issue by neerajkamdar** [tunapanda/wp-remote-sync#3]
I just tried installing then plugin and activating it. 

When I tried to activate it, I got the errors you can see in the attached file. Seems like there should be a file here:

/wp-remote-sync/ext/smartrecord/SmartRecord.php

which is missing / not in the repo. 

Is that supposed to be installed separately?

[WPContentSyncPluginActivationError.pdf](https://github.com/tunapanda/wp-remote-sync/files/66516/WPContentSyncPluginActivationError.pdf)

**Comment by limikael** [comment]
Hi @neerajkamdar, thanks for testing!

It uses [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). I added some instructions in the readme related to this. Also pasting them here for convenience:

If you clone the repository, you need to do so using any of these methods:
  1. You can clone it using `git clone --recusrive`.
  2. You can clone it without `--recursive`, and after do `git submodule init` and `git submodule update` inside the cloned folder.

Let me know how it works!

**Comment by neerajkamdar** [comment]
Thanks @limikael ... works almost perfect now. 

When I pulled the content from content.tunapanda.org, I got a couple of warnings:

Warning: Illegal string offset 'file' in /Applications/MAMP/htdocs/tunapanda/wordpress/wp-content/plugins/wp-remote-sync/src/syncers/AttachmentSyncer.php on line 46

Warning: Illegal string offset 'sizes' in /Applications/MAMP/htdocs/tunapanda/wordpress/wp-content/plugins/wp-remote-sync/src/syncers/AttachmentSyncer.php on line 47

It happened on many files - I've attached a sample with detailed call stack. They are just warnings, not a fatal errors - I think the resources still downloaded.  

Also the h5p content didn't download. Is that still work in progress?

[WPContentSyncPluginActivationError-2.pdf](https://github.com/tunapanda/wp-remote-sync/files/66580/WPContentSyncPluginActivationError-2.pdf)

**Comment by neerajkamdar** [comment]
Ignore the H5P content not downloading. I hadn't installed the H5P plugin so obviously it didn't download the content :)

Its working after I installed the plugin and installed the H5P content types.

**Comment by limikael** [comment]
Ohh... the warnings are probably due to the fact that I have warnings turned off locally... That's bad... Keeping the issue open and on me...

**Comment by limikael** [comment]
Think these warning should no longer be there, so closing... Let me know if they appear again...
