### ISSUE TITLE
Wp-remote-sync: This is the error i'm getting when i try to sync.

### ISSUE THREAD

**Issue by munga4** [tunapanda/wp-remote-sync#30]
![image](https://cloud.githubusercontent.com/assets/8983198/19882556/92e2e2f0-a01f-11e6-9fcb-f8bca70162f9.png)

**Comment by limikael** [comment]
Please put the screenshot in this bug: https://github.com/tunapanda/wp-remote-sync/issues/29 since it is the same bug.
