### ISSUE TITLE
Pulling H5P content fails when local H5P library is a higher version than remote

### ISSUE THREAD

**Issue by neerajkamdar** [tunapanda/wp-remote-sync#4]
I had an issue where when I pulled the H5P content from remote, it failed as my local H5P.DragText was at version 1.4.0 while the remote was at 1.3.1. It also fails at that point instead of skipping and continuing with the rest of the download. 

I modified the query in the _findH5pLibraryByName_ function in _H5pSyncers.php_ to allow the sync to continue if the local version of the particular H5P library is ahead of the remote version as below:

```
$q=$wpdb->prepare(
			"SELECT * ".
			"FROM   wp_h5p_libraries ".
			"WHERE  name=%s ".
			"AND    ( major_version > %s ".
			"         OR ( major_version = %s AND minor_version > %s )".
			"         OR ( major_version = %s AND minor_version = %s AND patch_version >= %s )".
			"       ) ",
			$name,
			$major_version,
			$major_version,
			$minor_version,
			$major_version,
			$minor_version,
			$patch_version);
```

I was not sure if I should commit this. Is an exact version match necessary for content compatibility?

**Comment by limikael** [comment]
The key question is this:

Is an exact version match necessary for content compatibility?

And the answer is that I don't know exactly. However, one thing comes to mind. At first glance, it makes sense as you do to allow a newer version to work as a substitute for an older one. But. In this setup, if I would later push the changes to the server, then my local content would be based on a new version, and the server would no be able to handle this. So while it makes sense that a new version of a library works as a replacement for an old one, this creates a situation where the content can't be sent back to the server. Unless we skip the version check all together, and I think this could have strange and unexpected consequences.

Hm... Maybe we can keep the version check, and instead attack the problem that it "fails hard" as soon as one resource fails. Instead it should continue with the rest of the content. What do you think about this?

**Comment by neerajkamdar** [comment]
Yes .. I didn’t consider pushing changes to the server. 

I’m not sure how far H5P modules are backwards compatible. Is it just minor versions or also major versions? Once we find out we could address this better. I couldn’t find an answer on the H5P website.

If future versions in H5P are backward compatible, we could make sure the remote version is equal to or ahead of local version before pushing - similar to the modified check I tested yesterday for pulling the content. 

In regards to the failing hard on one version incompatibility, I agree that we should just have a warning that this piece of content was skipped due to version incompatibility and then it should continue with the remaining content. It makes sense as the different pieces of content are independent of each other so a hard fail is not necessary.

**Comment by limikael** [comment]
Hm... So then we are back to what we have right now, yes? If the local version is ahead or equal to the remote version, and also the remote version is ahead or equal to the local version, then this must mean that the local and remote versions are the same? And this is the only scenario we can handle with confidence, so we might as well keep it the way it is, with an equality check?

This comment is related to the version check, regarding the failing hard part it seems we are on the same page.

**Comment by neerajkamdar** [comment]
Currently it looks for an exact match of version - major version + minor version + patch version should be exactly the same.  

I think we can come back to this once we find out more on the H5P backward compatibility - if the modules are backwards compatible, we can add the check for equal to or ahead versions on push and pull and handle accordingly. 

For now let’s leave it as exact match.

**Comment by limikael** [comment]
Sounds good...

It would make sense to only compare the major or major+minor versions... Maybe we can have a setting for this?

But regardless of what we compare, the comparison would always be done with =, never with < or >. The reason for this is because if `local_version > remote_version`, then it follows that `remote_version < local_version`. I.e. if the pull works, the push would fail. If the push works, the pull would fail. It is not useful to have an environment where only one of the operations pull and push works, for the system to be useful they both have to work. Makes sense?

**Comment by neerajkamdar** [comment]
Yes .. if the same function is used for both push and pull then < or > wouldn’t work. 

But if we decide to let it work for ahead version or same version, then we could check if: 
```local_version >= remote_version``` for pull and 
```remote_version >= local_version``` for push.     

A setting maybe a good option, especially for development.

**Comment by limikael** [comment]
Hm, I see how this would make sense from a technical perspective... But...
From a user perspective... Say I have a newer local version than what is on
the server... Then I could pull... But, I wouldn't be able to push it back
to the server afterwards, right?

**Comment by neerajkamdar** [comment]
Yes .. I didn’t think of it with that perspective. 

Also, from past experience whenever I’ve updated H5P libraries, some of the old content has to be resaved / recreated to work again, so with lots of content, updating H5P libraries often may not be feasible.

I think the main issue will be when someone clones this repo to work - then installs H5P - they will download the latest H5P library version by default, which may not be in sync with the remote version. When they pull the remote data, they will come across this issue. This is what happened to me. 

I think your idea of having the a setting to force the sync even if the versions are not the same sounds like a good compromise.

**Comment by limikael** [comment]
I know what you mean, I have had the same issue and it is a bit of a
hurdle... The setting to continue even if the versions are different is
probably our best option...

Maybe in the future we could have automateld install of H5P libraries to
match the version when syncing? I think I have read somewhere that H5P is
working on getting the library upgrade to be smoother, so this might be
possible without too much hackning in the future?

**Comment by neerajkamdar** [comment]
Sounds good to me.

**Comment by limikael** [comment]
Ok... closing this for now...
